### ISSUE TITLE
Exception (Exception: Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_jni.so': dlopen failed: library "libtensorflowlite_jni.so" not found)

### ISSUE THREAD

**Issue by AbdulRehman5592** [CaptainDario/lite_rt_for_flutter#1]
hello i tried to run your select_ops_test example and this is the error it is giving me...i currently am facing the select ops issue while trying to run my model....I havent added paths in the pubspec.yaml well cause i did not had the mentioned files locally...i noticed those were a part of package hence they will not cause an issue(and i dont think they did)..the issue is the missing .so file....any help would be appreciated

[pubspec.txt](https://github.com/user-attachments/files/19269316/pubspec.txt)

**Comment by AbdulRehman5592** [comment]
the library addresses are given in libs.dart

**Comment by dariyooo** [comment]
Can you paste your pubspec as text here?

You need to add the library-packages you need as mentioned in the README.
The additional packages include the needed binaries.
Currently, this package is not hosted on pub (will do so soon), so you need to add the git reference. 

``` yaml
dependencies:
  # The binding between Flutter/Dart and native code
  lite_rt_for_flutter:
    version: <THE_VERSION_YOU_WANT>

  # Additionally, you need the base LiteRT libraries (includes XNNPack delegate)
  lite_rt_for_flutter_libs:
    version: <THE_VERSION_YOU_WANT>
  # optionally you can set specific versions per platform
  lite_rt_for_flutter_libs_{android|macos|...}:
    version: <THE_VERSION_YOU_WANT>
```

and

```yaml
dependencies:
  # Include the flex delegate
  lite_rt_for_flutter_libs_flex:
    version: <THE_VERSION_YOU_WANT>
```

You can get package references from [here](https://github.com/CaptainDario/lite_rt_for_flutter_libs).
